### ISSUE TITLE
Add file to matlab directory

### ISSUE THREAD

**Issue by michaelpacer** [DanielNScott/ct_bact#6]
Currently I think this is the only file are not included in the directory but are needed to make the code work: 

* `NonHomPoisson`

**Comment by DanielNScott** [comment]
done, though it's now gen_poisson.m and it's in my stochastic_processes repo. (I've got more that I'll probably add later, and they're not strictly for ct_bact, hence the different repo)

**Comment by michaelpacer** [comment]
Understandable, though unfortunate that there's no git equivalent of hard
links (ala ln) so that you could link the dependencies and have automatic
changes propagate back and forth

also — I'm planning on refactoring some of this into python, so I may leave
that in the ct_bact repo so that I can work on it in the same folder
structure

I also may pull in the current version of the matlab code to my fork just
so that I can more easily manage that port in one place

**Comment by DanielNScott** [comment]
yeah, both of those things make sense to me.
